### ISSUE TITLE
Will this work with spree 2.2 and rails 4?

### ISSUE THREAD

**Issue by souravsumit21** [theghostwhoforks/spree_payuin#1]

**Comment by theghostwhoforks** [comment]
This has been tested on [spree 1.2.0](https://github.com/theghostwhoforks/spree_payuin/blob/master/spree_payuin.gemspec#L17) and Rails 3.2.x

I reckon you will need to upgrade this extension to get it working with Spree 2.2 . Do let me know if you require any further information around the PayUIn extension.

If you end up upgrading the extension, pull requests are welcome! 

Thanks
